const userLogin = require('../spec/User/login.spec')
const createCategory = require('../spec/Category/createCategory.spec')
const deleteCategory = require('../spec/Category/deleteCategory.spec')
const getCategoryId = require('../spec/Category/getCategoryId.spec')
const getCategoryList = require('../spec/Category/getCategoryList.spec')
const putCategory = require('../spec/Category/putCategory.spec')
const createUnit = require('../spec/Units/createUnit.spec')
const deleteUnit = require('../spec/Units/deleteUnit.spec')
const getUnitId = require('../spec/Units/getUnitId.spec')
const getUnitList = require('../spec/Units/getUnitList.spec')
const putUnit = require('../spec/Units/putUnit.spec')

async function regression_suite() {
    await userLogin()
    await createCategory()
    await deleteCategory()
    await getCategoryId() 
    await getCategoryList()
    await putCategory()
    await createUnit()
    await deleteUnit()
    await getUnitId()
    await getUnitList()
    await putUnit()
}